// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221228151630_update_culomns")]
    partial class updateculomns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Models.Customer", b =>
                {
                    b.Property<string>("customerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("customerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("WebApi.Models.FactoriesToCustomer", b =>
                {
                    b.Property<int>("GroupCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupCode"));

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FactoryCode")
                        .HasColumnType("int");

                    b.HasKey("GroupCode");

                    b.HasIndex("CustomerId");

                    b.HasIndex("FactoryCode");

                    b.ToTable("FactoriesToCustomers");
                });

            modelBuilder.Entity("WebApi.Models.Factory", b =>
                {
                    b.Property<int>("actoryCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("actoryCode"));

                    b.Property<string>("factoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("groupCode")
                        .HasColumnType("int");

                    b.Property<int?>("groupCode1")
                        .HasColumnType("int");

                    b.HasKey("actoryCode");

                    b.HasIndex("groupCode1");

                    b.ToTable("Factories");
                });

            modelBuilder.Entity("WebApi.Models.Group", b =>
                {
                    b.Property<int>("groupCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("groupCode"));

                    b.Property<string>("groupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("groupCode");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("WebApi.Models.FactoriesToCustomer", b =>
                {
                    b.HasOne("WebApi.Models.Customer", "Customers")
                        .WithMany("FactoriesToCustomer")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Models.Factory", "Factories")
                        .WithMany("FactoriesToCustomer")
                        .HasForeignKey("FactoryCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customers");

                    b.Navigation("Factories");
                });

            modelBuilder.Entity("WebApi.Models.Factory", b =>
                {
                    b.HasOne("WebApi.Models.Group", "group")
                        .WithMany("Factories")
                        .HasForeignKey("groupCode1");

                    b.Navigation("group");
                });

            modelBuilder.Entity("WebApi.Models.Customer", b =>
                {
                    b.Navigation("FactoriesToCustomer");
                });

            modelBuilder.Entity("WebApi.Models.Factory", b =>
                {
                    b.Navigation("FactoriesToCustomer");
                });

            modelBuilder.Entity("WebApi.Models.Group", b =>
                {
                    b.Navigation("Factories");
                });
#pragma warning restore 612, 618
        }
    }
}
