// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230102093201_fixingFactoriesToCustomer2")]
    partial class fixingFactoriesToCustomer2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Models.Customer", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("WebApi.Models.FactoriesToCustomer", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FactoryCode")
                        .HasColumnType("int");

                    b.Property<int>("GroupCode")
                        .HasColumnType("int");

                    b.HasKey("CustomerId", "FactoryCode");

                    b.HasIndex("FactoryCode");

                    b.HasIndex("GroupCode");

                    b.ToTable("FactoriesToCustomer");
                });

            modelBuilder.Entity("WebApi.Models.Factory", b =>
                {
                    b.Property<int>("FactoryCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FactoryCode"));

                    b.Property<string>("FactoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupCode")
                        .HasColumnType("int");

                    b.HasKey("FactoryCode");

                    b.HasIndex("GroupCode");

                    b.ToTable("Factories");
                });

            modelBuilder.Entity("WebApi.Models.Group", b =>
                {
                    b.Property<int>("GroupCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupCode"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroupCode");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("WebApi.Models.FactoriesToCustomer", b =>
                {
                    b.HasOne("WebApi.Models.Customer", "Customer")
                        .WithMany("FactoriesToCustomer")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Models.Factory", "Factory")
                        .WithMany("FactoriesToCustomer")
                        .HasForeignKey("FactoryCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Factory");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("WebApi.Models.Factory", b =>
                {
                    b.HasOne("WebApi.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("WebApi.Models.Customer", b =>
                {
                    b.Navigation("FactoriesToCustomer");
                });

            modelBuilder.Entity("WebApi.Models.Factory", b =>
                {
                    b.Navigation("FactoriesToCustomer");
                });
#pragma warning restore 612, 618
        }
    }
}
